### ISSUE TITLE
Rely Webpage Not loading

### ISSUE THREAD

**Issue by huangs1** [baldeosinghm/rely#1]
Hello Mr. Baldeosinghm,

I was super interested in your project! The concept is amazing! However, I was not able to reach your application using the following url: http://45.56.102.63/

Could you please take a look at the issue?

Thank you!
Spencer Huang

**Comment by baldeosinghm** [comment]
How am I now seeing this and did you really expect that to work haha.  An inventive way of reaching out my man!
